name = "Swag!!"
description = "Awesome theme!!"
license = "GNU General Public License v3.0"
licenselink = "https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/LICENSE"
homepage = "https://github.com/kakawait/hugo-tranquilpeak-theme"
tags = ["blog", "minimal", "responsive", "personal", "customizable", "creative", "fontawesome", "highlight.js"]
features = ["blog", "themes", "disqus", "minimal", "responsive", "font awesome", "highlight.js"]
min_version = 0.53

[author]
  name = "Thibaud Leprêtre"
  homepage = "https://github.com/kakawait"

[original]
  name = "Tranquilpeak"
  homepage = "https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak"
  repo = "https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak.git"
